### ISSUE TITLE
no wrapping for certain type of character set

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#67] opened 2020-11-15 13:56 UTC
for one of the answers, there was a strange type of hidden character (possibly a space!) that prevented correct wrapping of the paragraphs. is there a way to issue a warning or check what causes such a problem?

![Screenshot 2020-11-15 at 12 21 00](https://user-images.githubusercontent.com/5281249/99186707-7ba2cb00-2752-11eb-8661-f2123805a1c6.png)

**Comment by SanliFaez** [comment] 2020-11-15 13:57
interestingly, there was no problem with the abstract, even though that also used the same charset.

**Comment by aquilesC** [comment] 2020-11-15 16:45
How can you reproduce this? Or what steps lead to it? It is very strange...

**Comment by SanliFaez** [comment] 2020-11-15 18:50
the strange character sits in this text. https://gitlab.com/s4fnl/climate-facts/-/issues/57#note_435562993
I copied it to a text editor and changed encoding to ascii and back to unicode. then it was solved. but also killed a lot of special characters, which was a pity

**Comment by aquilesC** [comment] 2020-11-16 08:23
I checked adding the ë to financiële and it seems it does not break the layout. I can't really tell what caused the issue, tried copy/pasting into a new article and couldn't reproduce the issue, so it is very strange. 

My only guess is that perhaps the line/endings got messed up? Could you reproduce the error and leave it as a draft so I can take a look at what is going on?

**Comment by aquilesC** [comment] 2021-02-06 10:49
I am closing this since the error didn't appear again. Did a check to the encoding and everything looks fine. If the error pups up again, feel free to reopen.

**Closed by aquilesC** 2021-02-06 10:49 UTC
Labels: Wagtail
